# This is an example configuration file for the integration service.
# Please copy this file to conf/config.yaml and edit it to your needs.

# The integrations list to load into the integration framework.
# You can add as many integrations as you want, and you can use the same type of integration multiple times.
port:
  clientId: <client_id> # Can be loaded via environment variable: PORT_CLIENT_ID
  clientSecret: <client_secret> # Can be loaded via environment variable: PORT_CLIENT_SECRET
integrations:
  # The name of the integration.
  - identifier: "my_integration"
    # The type of the integration.
    type: "kafka"
    # The configuration of the integration.
    config:
      bootstrapServers: "localhost:9092"
  - identifier: "pager_duty"
    type : "pager_duty"
    config: 
      token: "TOKEN"