[tool.poetry]
name = "freamwork"
version = "0.1.0"
description = "A short description of the project"
authors = ["Daniel Sinai (daniel@getport.io)", "Yair Siman-Tov (yair@getport.io)"]
packages = [
    { include = "framework", from = "." },
]

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^1.10.8"
requests = "^2.31.0"
loguru = "^0.7.0"
jq = "^1.4.1"
pyyaml = "^6.0"
werkzeug = "^2.3.4"
fastapi = "^0.96.0"
uvicorn = "^0.22.0"
click = "^8.1.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2"
black = "^23.3.0"
autopep8 = "^2.0.0"
pylint = "^2.15.8"
mypy = "^1.3.0"
pre-commit = "^3.3.2"


[tool.poetry.scripts]
portconnect = "framework.cli:portlink"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 88
target-version = ['py39', 'py310', 'py311']
include = '\.pyi?$'
exclude = '''
/(
  \.toml
  |\.sh
  |\.git
  |\.ini
  |Dockerfile
)/
'''