createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: project
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .key
          title: .name
          blueprint: '"jiraProject"'
          properties:
            url: (.self | split("/") | .[:3] | join("/")) + "/projects/" + .key
            totalIssues: .insight.totalIssueCount

  - kind: board
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .id | tostring
          title: .name
          blueprint: '"jiraBoard"'
          properties:
            url: (.self | split("/") | .[:3] | join("/")) + "/jira/software/c/projects/" + .location.projectKey + "/boards/" + (.id | tostring)
            type: .type
          relations:
            project: if .location.projectId == null then '' else .location.projectId | tostring end

  - kind: sprint
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .id | tostring
          title: .name
          blueprint: '"jiraSprint"'
          properties:
            url: .self
            state: .state
            startDate: .startDate
            endDate: .endDate
          relations:
            board: if .originBoardId then .originBoardId | tostring else '' end

  - kind: issue
    selector:
      query: "true"
      jql: "statusCategory != done"
      source: "sprint"
      sprintState: "active"
    port:
      entity:
        mappings:
          identifier: .key
          title: .fields.summary
          blueprint: '"jiraIssue"'
          properties:
            url: (.self | split("/") | .[:3] | join("/")) + "/browse/" + .key
            status: .fields.status.name
            issueType: .fields.issuetype.name
            components: .fields.components
            assignee: .fields.assignee.emailAddress
            reporter: .fields.reporter.emailAddress
            creator: .fields.creator.emailAddress
            priority: .fields.priority.name
            labels: .fields.labels
            created: .fields.created
            updated: .fields.updated
          relations:
            sprint: if .fields.sprint.id then .fields.sprint.id | tostring else '' end
            project: .fields.project.key
            parentIssue: .fields.parent.key
            subtasks: .fields.subtasks | map(.key)
