createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: project
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .key
          title: .name
          blueprint: '"jiraProject"'
          properties:
            url: (.self | split("/") | .[:3] | join("/")) + "/projects/" + .key
            totalIssues: .insight.totalIssueCount

  - kind: sprint
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .name + "-" + (.id | tostring) | gsub("[^A-Za-z0-9@_.:\\\\/=-]"; "-")
          title: .name
          blueprint: '"jiraSprint"'
          properties:
            url: .self
            state: .state
            startDate: .startDate
            endDate: .endDate

  - kind: issue
    selector:
      query: "true"
      jql: "(statusCategory != Done) OR (created >= -1w) OR (updated >= -1w)"
      source: "sprint"
      sprintState: "active"
    port:
      entity:
        mappings:
          identifier: .key
          title: .fields.summary
          blueprint: '"jiraIssue"'
          properties:
            url: (.self | split("/") | .[:3] | join("/")) + "/browse/" + .key
            status: .fields.status.name
            issueType: .fields.issuetype.name
            components: .fields.components
            assignee: .fields.assignee.emailAddress
            reporter: .fields.reporter.emailAddress
            creator: .fields.creator.emailAddress
            priority: .fields.priority.name
            labels: .fields.labels
            created: .fields.created
            updated: .fields.updated
            resolutionDate: .fields.resolutiondate
          relations:
            sprint: if .fields.sprint.id then .fields.sprint.name + "-" + (.fields.sprint.id | tostring) | gsub("[^A-Za-z0-9@_.:\\\\/=-]"; "-") else "" end
            project: .fields.project.key
            parentIssue: .fields.parent.key
            subtasks: .fields.subtasks | map(.key)
