name: Pull Request Labeling

on:
  - pull_request_target

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create dynamic labeler configuration
        env:
          yamlfile: .github/labeler.yml
        run: |
          find integrations -mindepth 1 -maxdepth 1 -type d | grep -v '/\.' | awk -F'/' '{print $NF}' | jq -R -s -c 'split("\n")[:-1]' > integrations.json
          echo "Integrations:"
          cat integrations.json
          touch ${{ env.yamlfile }}
          echo "Add dynamic integration labels to ${{ env.yamlfile }}"
          jq -r '.[]' integrations.json | while read integration; do
            label="${integration//\//-}"
            if [ "${#label}" -gt 63 ]; then
                echo "Label is longer than 63 characters: $label"
                label="${label:0:63}"
                echo "Trimmed label to 63 characters: $label"
            fi

            echo "- $integration -> $label"

            cat >> ${{ env.yamlfile }} << EOF
          $label:
            - changed-files:
              - any-glob-to-any-file: 'integrations/$integration/**'
          EOF
          done

          echo "Output file"
          cat ${{ env.yamlfile }}

      - name: Apply labels
        uses: actions/labeler@v5
        with:
          sync-labels: true
          config-path: .github/labeler.yml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@v0.5.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          sizes: >
            {
              "0": "XS",
              "20": "S",
              "50": "M",
              "200": "L",
              "800": "XL",
              "2000": "XXL"
            }
