name: Release framework
on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: write

env:
  PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
jobs:
  publish_ocean:
    name: Publish Ocean
    runs-on: ubuntu-latest
    steps:
      - name: Install python version
        uses: gabrielfalcao/pyenv-action@v11
        with:
          default: "3.11"
          command: pip install -U pip  # upgrade pip after installing python 
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Make install and build
        run: | 
            make install
            make build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ env.PYPI_USERNAME }}
          password: ${{ env.PYPI_PASSWORD }}
          packages-dir: ${{github.workspace}}/dist
